export const willaya = [
  'Adrar',
  'Chlef',
  'Laghouat',
  'Oum El Bouaghi',
  'Batna',
  'Béjaïa',
  'Biskra',
  'Bechar',
  'Blida',
  'Bouira',
  'Tamanrasset',
  'Tbessa',
  'Tlemcen',
  'Tiaret',
  'Tizi Ouzou',
  'Alger',
  'Djelfa',
  'Jijel',
  'Setif',
  'Saefda',
  'Skikda',
  'Sidi Bel Abbes',
  'Annaba',
  'Guelma',
  'Constantine',
  'Medea',
  'Mostaganem',
  "M'Sila",
  'Mascara',
  'Ouargla',
  'Oran',
  'El Bayadh',
  'Illizi',
  'Bordj Bou Arreridj',
  'Boumerdes',
  'El Tarf',
  'Tindouf',
  'Tissemsilt',
  'El Oued',
  'Khenchela',
  'Souk Ahras',
  'Tipaza',
  'Mila',
  'Ain Defla',
  'Naama',
  'Ain Temouchent',
  'Ghardaefa',
  'Relizane',
  "El M'ghair",
  'El Menia',
  'Ouled Djellal',
  'Bordj Baji Mokhtar',
  'Béni Abbès',
  'Timimoun',
  'Touggourt',
  'Djanet',
  'In Salah',
  'In Guezzam',
];

export const serviceAccessibilityList = [
  'ELEVATOR',
  'INTERCOM',
  'CHIP PORT',
  'GUARDIAN',
  'PARKING',
  'COLLECTION PARABLES',
  'INTERNET',
];

export const hygieneList = [
  'WATER_ANK',
  'WATER PUMP',
  'BATHROOM',
  'SEPARATE TOILET',
  'NO SEPARATE TOILET',
];

export const piecesList = ['SALON', 'TERRACE', 'BALCONY', 'CLOSETS', 'GARDEN'];

export const publicServcieList = [
  'PRIMARY SCHOOL',
  'SECONDARY SCHOOL',
  'HIGH SCHOOL',
  'BALCONY',
  'BANK',
  'PUBLIC GARDEN',
  'COURT',
  'TOWN HALL',
];

export const quillConfig = {
  toolbar: {
    container: [
      ['bold', 'italic', 'underline', 'strike'],
      ['code-block'],
      [{ header: 1 }, { header: 2 }],
      [{ list: 'ordered' }, { list: 'bullet' }],
      ['clean'],
    ],
  },
};
