export const willaya = [
  'Tous',
  'Adrar',
  'Chlef',
  'Laghouat',
  'Oum El Bouaghi',
  'Batna',
  'Béjaïa',
  'Biskra',
  'Bechar',
  'Blida',
  'Bouira',
  'Tamanrasset',
  'Tbessa',
  'Tlemcen',
  'Tiaret',
  'Tizi Ouzou',
  'Alger',
  'Djelfa',
  'Jijel',
  'Setif',
  'Saefda',
  'Skikda',
  'Sidi Bel Abbes',
  'Annaba',
  'Guelma',
  'Constantine',
  'Medea',
  'Mostaganem',
  "M'Sila",
  'Mascara',
  'Ouargla',
  'Oran',
  'El Bayadh',
  'Illizi',
  'Bordj Bou Arreridj',
  'Boumerdes',
  'El Tarf',
  'Tindouf',
  'Tissemsilt',
  'El Oued',
  'Khenchela',
  'Souk Ahras',
  'Tipaza',
  'Mila',
  'Ain Defla',
  'Naama',
  'Ain Temouchent',
  'Ghardaefa',
  'Relizane',
  "El M'ghair",
  'El Menia',
  'Ouled Djellal',
  'Bordj Baji Mokhtar',
  'Béni Abbès',
  'Timimoun',
  'Touggourt',
  'Djanet',
  'In Salah',
  'In Guezzam',
];

export const serviceAccessibilityList = [
  'Ascenseur',
  'Interphone',
  'Puce Port',
  'Gardien',
  'Parking',
  'Internet',
  'Parabole Collectif',
];

export const hygieneList = [
  "Réservoir D'eau",
  'Pompe A Eau',
  'Toilettes Séparées',
  'Toilettes Non Séparées',
  'Salle De Bain',
  'chauffe eau',
];

export const piecesList = ['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'Plus'];

export const publicServcieList = [
  'Jardin Public',
  'Tribunal',
  'École Primaire',
  'École secondaire',
  'Lycée',
  'Banque',
  'Mosquée',
  'Université',
  'Transport',
  'Hospitalier',
  'Clinique',
  'Commerces',
];

export const quillConfig = {
  toolbar: {
    container: [
      ['bold', 'italic', 'underline', 'strike'],
      ['code-block'],
      [{ header: 1 }, { header: 2 }],
      [{ list: 'ordered' }, { list: 'bullet' }],
      ['clean'],
    ],
  },
};
export const avances = [
  'sans avances',
  '1 mois',
  '2 mois',
  '3 mois',
  '4 mois',
  '5 mois',
  '6 mois',
  '7 mois',
  '8 mois',
  '9 mois',
  '10 mois',
  '11 mois',
  '12 mois',
];
